//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.25 at 07:11:03 PM CET 
//


package be.tbs.mgf.schemas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.tbs.mgf.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.tbs.mgf.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StatusReply }
     * 
     */
    public StatusReply createStatusReply() {
        return new StatusReply();
    }

    /**
     * Create an instance of {@link StatusProperty }
     * 
     */
    public StatusProperty createStatusProperty() {
        return new StatusProperty();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link LeaveRequest }
     * 
     */
    public LeaveRequest createLeaveRequest() {
        return new LeaveRequest();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link StatusRequest }
     * 
     */
    public StatusRequest createStatusRequest() {
        return new StatusRequest();
    }

    /**
     * Create an instance of {@link LeaveReply }
     * 
     */
    public LeaveReply createLeaveReply() {
        return new LeaveReply();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Pong }
     * 
     */
    public Pong createPong() {
        return new Pong();
    }

    /**
     * Create an instance of {@link Ping }
     * 
     */
    public Ping createPing() {
        return new Ping();
    }

    /**
     * Create an instance of {@link PlayerDescriptor }
     * 
     */
    public PlayerDescriptor createPlayerDescriptor() {
        return new PlayerDescriptor();
    }

    /**
     * Create an instance of {@link Reply }
     * 
     */
    public Reply createReply() {
        return new Reply();
    }

    /**
     * Create an instance of {@link JoinRequest }
     * 
     */
    public JoinRequest createJoinRequest() {
        return new JoinRequest();
    }

    /**
     * Create an instance of {@link JoinReply }
     * 
     */
    public JoinReply createJoinReply() {
        return new JoinReply();
    }

}
