//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.25 at 07:11:03 PM CET 
//


package be.tbs.mgf.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Reply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Reply">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tbs.be/mgf/schemas}Message">
 *       &lt;sequence>
 *         &lt;element name="Pong" type="{http://www.tbs.be/mgf/schemas}Pong"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reply", propOrder = {
    "pong"
})
@XmlSeeAlso({
    JoinReply.class,
    StatusReply.class,
    LeaveReply.class
})
public class Reply
    extends Message
{

    @XmlElement(name = "Pong", required = true)
    protected Pong pong;

    /**
     * Gets the value of the pong property.
     * 
     * @return
     *     possible object is
     *     {@link Pong }
     *     
     */
    public Pong getPong() {
        return pong;
    }

    /**
     * Sets the value of the pong property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pong }
     *     
     */
    public void setPong(Pong value) {
        this.pong = value;
    }

}
